pub const DEFAULT_SESSION_EXPIRY_INTERVAL: u32 = 0;
pub const DEFAULT_RECEIVE_MAXIMUM: u16 = 65_535;
pub const DEFAULT_TOPIC_ALIAS_MAXIMUM: u16 = 0;
pub const DEFAULT_REQUEST_RESPONSE_INFORMATION: bool = false;
pub const DEFAULT_REQUEST_PROBLEM_INFORMATION: bool = true;
pub const DEFAULT_WILL_DELAY_INTERVAL: u32 = 0;
pub const DEFAULT_PAYLOAD_FORMAT_INDICATOR: bool = false;
