use crate::QoS;

pub const DEFAULT_MAXIMUM_QOS: QoS = QoS::ExactlyOnce;
pub const DEFAULT_PAYLOAD_FORMAT_INDICATOR: bool = false;
pub const DEFAULT_RECEIVE_MAXIMUM: u16 = 65_535;
pub const DEFAULT_REQUEST_PROBLEM_INFORMATION: bool = true;
pub const DEFAULT_REQUEST_RESPONSE_INFORMATION: bool = false;
pub const DEFAULT_RETAIN_AVAILABLE: bool = true;
pub const DEFAULT_SESSION_EXPIRY_INTERVAL: u32 = 0;
pub const DEFAULT_SHARED_SUBSCRIPTION_AVAILABLE: bool = true;
pub const DEFAULT_TOPIC_ALIAS_MAXIMUM: u16 = 0;
pub const DEFAULT_WILCARD_SUBSCRIPTION_AVAILABLE: bool = true;
pub const DEFAULT_WILL_DELAY_INTERVAL: u32 = 0;
pub const DEFAULT_SUBSCRIPTION_IDENTIFIER_AVAILABLE: bool = true;